language: python
  python:
    - '2.7'
  install: pip install -r requirements.txt;export DJANGO_SETTINGS_MODULE=project_curiocity.settings.local
  script: python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: sU0b+4PcLOC9AXjncS+maWxxBpkP1syZ19EMNXDgZzgxjuBN9gSrDIUBF0SwIRhsFgBnXAbr8s5fv9bBKMVrrFLhttXodEXlEFLwI1xUAUtqX86vEb0rNrWG/s5joBaCWavoWpI3YEmRNyPJ6XR03w50gHdkBFyX/4zZayE1VV4=
  app: 
    master: project-curiocity
    development: project-curiocity-beta
  on:
    repo: ULRL-Lab/curiocity-test
