language: python
python:
- '2.7'
install: pip install -r requirements.txt;export DJANGO_SETTINGS_MODULE=project_curiocity.settings.local
script: python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: tqu10kQksAKbM9DW4E+F41Ba/aIzNjZ/9Nf+nhdiQzKSLW67jEjmPOwiLQW9eRpZG4nltW5y6zHJH/ieUqmZo+U2gz6lgfCaTUT5HC302Vf/+ExFAWI7MYBjpo81hw4jlj9nShHVyLJOfjCroUjzKQKbOiQFPTt8w2CMsT2ILpQ=
  app:
    master: project-curiocity
    development: project-curiocity-beta
  on:
    repo: ULRL-Lab/curiocity-test
